version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
    - echo "Install completed"
# If needed, you can add commands for dependency installation
  build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: .